version: '3.7'

services:
  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul
    restart: always
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
  protoconf-webhook:
    image: ghcr.io/protoconf/protoconf-webhook:v0
    container_name: protoconf-webhook
    restart: always
    networks:
      - consul
    ports:
      - "9000:9000"
    env_file:
      - .env

networks:
  consul:
    driver: bridge
